[project]
name = "pyield"
authors = [{ name = "Carlos Carvalho", email = "carlos.carvalho.jr@gmail.com" }]
description = "Polars-powered toolkit for Brazilian fixed income analysis"
readme = "README.md"
requires-python = ">=3.12"
keywords = ["fixed-income", "brazil", "finance", "analysis", "bonds"]
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Financial and Insurance Industry",
    "Topic :: Office/Business :: Financial :: Investment",
]
dependencies = [
    "polars>=1.39.0",
    "lxml>=6.0.0",
    "requests>=2.31.0",
    "fastexcel>=0.19.0",
    "tzdata>=2024.1; platform_system == 'Windows'",
]
version = "0.55.0"

[project.urls]
Homepage = "https://github.com/crdcj/PYield"
Documentation = "https://crdcj.github.io/PYield"
Source = "https://github.com/crdcj/PYield"
"Bug Tracker" = "https://github.com/crdcj/PYield/issues"

[dependency-groups]
dev = [
    "python-dotenv[cli]",
    "ipykernel",
    "pytest",
    "ruff",
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]",
    "lxml-stubs",
    "ty"
]

[build-system]
requires = ["uv_build>=0.12.3,<0.13"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "pyield"
module-root = ""

[tool.pytest.ini_options]
testpaths = ["tests", "pyield"]
addopts = "--doctest-modules"
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"

[tool.ty.src]
include = ["pyield"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
preview = true
select = ["I", "F", "E", "W", "PL", "PT"]
ignore = ["E501"]

[tool.ruff.format]
docstring-code-format = true
