line-length = 88
indent-width = 4
target-version = "py312"
extend-include = ["*.ipynb"]

[lint]
preview = true
select = ["I", "F", "E", "W", "PL", "PT"]

[format]
docstring-code-format = true
docstring-code-line-length = 88